export const TASKS_ACTIONS = {
  DELETE_TASK: "DELETE_TASK",
  TOGGLE_CHECKBOX: "TOGGLE_CHECKBOX",
  ADD_TASK: "ADD_TASK",
  FILTER_TASKS: "FILTER_TASKS",
  CHECK_REGISTRATION: "CHECK_REGISTRATION",
  LOGOUT: "LOGOUT",
};
